### ISSUE TITLE
Create basic docs in restructuredText and publish to ReadTheDocs

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/civic-scraper#75]
Set up documentation using sphinx, restructuredText and ReadTheDocs.

Flesh out the initial docs site based on the sections covered in this [GDoc](https://docs.google.com/document/d/1duv10C7DPu7VWa00_aW0DEBFiYWXaxSZfTjQiNmAIa4/edit?usp=sharing) and the below notes:

* End user docs
* Contributor docs
* Roadmap (things we're currently working on and what's planned)
* Ways to Contribute and How to Contribute

## Tasks

- [x] Convert `README.md` into restructuredText and update as need to reflect refactorings (#68) and other additions (e.g. CLI runner).
- [x] Add MANIFEST.ini
- [x] Add CONTRIBUTORS
- [x] Add HISTORY
- [x] Ensure API docs build from docstrings on public methods (which use Google Python Style)
- [x] Deploy to ReadTheDoc

## Refactor-related updates

> Most of these doc updates are needed in response to changes introduced in #68

### End-user docs

Update end-user docs as follows:

 - [x] Mention default cache directory (`~/.civic-scraper`) and ability to configure via`CIVIC_SCRAPER_DIR` env variable
 - [x] Remove mention of `AssetCollection.download` and update examples to show usage of `Asset.download` only
 - [x] Remove mentions througout page of parameters removed from `scrape` method (`csv_export`, 'append`, `target_dir`)
 - [x] Add mentions of paramaters added to `CivicPlusSite.__init__` method
