### ISSUE TITLE
Implement CLI using click

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/civic-scraper#76]
Implement a CLI interface using the [click][] library. 

[click]: https://click.palletsprojects.com/en/7.x/

The tool should include the following interface as a start:

```
# NOTE: All commands automatically generate a metadata CSV of assets

# Scrape current day for a site and generate metadata CSV
civic-scraper scrape --url <site URL>

# Scrape current day and download file assets (to CIVIC_SCRAPER DIR)
civic-scraper scrape --download --url <site URL>

# Scrape current day and cache scraping-related file artifacts (e.g. HTML from search result page)
civic-scraper scrape --cache  --url <site URL>

# Scrape current day for URLs listed in CSV (should contain "url" field)
civic-scraper scrape --file <sites.csv>

# Scrape between specific dates
civic-scraper scrape  --start=2020-01-10 --end=2020-01-31 --url <site URL>
```

## Tasks

- [x] Create cli.py that invokes runner with relevant options and includes logging
  - [x] caching artifacts
  - [x] dowloading assets
  - [x] scrape url from CLI
  - [x]  scrape urls from file
- [x] Create Runner
- [x] Ensure AssetCollections support standard list operations such as `.append` to enable merging of collections at CLI layer
